#!/bin/bash

# Requires:
#   cf_cli
#   jq
#   printf

declare -r InstanceGUIDHeader="INSTANCE GUID"
declare -r OrgGUIDHeader="ORG GUID"
declare -r OrgNameHeader="ORG NAME"
declare -r SpaceGUIDHeader="SPACE GUID"
declare -r SpaceNameHeader="SPACE NAME"
declare -r AppGUIDHeader="APP GUID"
declare -r AppNameHeader="APP NAME"
declare Result=0
declare -a OrgGUIDs
declare -a OrgNames
declare -a SpaceGUIDs
declare -a SpaceNames
declare -a AppGUIDs
declare -a AppNames
declare NumInstancesFound=0
declare PrintJSON=false
declare JQOptions="-r"

# Takes an instance ID and returns a newline separated list with the GUIDs for each app bound to this service instance.
app_guids_bound_to()
{
  local _instanceID="$1"
  if [[ -z ${_instanceID} ]]
    then set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  local ret=$(cf curl "/v2/service_instances/${_instanceID}/service_bindings" | jq ".resources[].entity.app_guid" "${JQOptions}" 2> /dev/null)
  Result=$?
  echo "${ret}"
}

#Takes an app GUID and returns that app's name
app_name_with_guid()
{
  local _appID="$1"
  if [[ -z ${_appID} ]]
    then set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  ret=$(cf curl "/v2/apps/${_appID}" | jq ".entity.name" "${JQOptions}")
  Result=$?
  echo "${ret}"
}

# Takes an instance GUID and returns the GUID of the space which this service instance exists in.
space_guid_for_service_instance()
{
  local _instanceID="$1"
  if [[ -z ${_instanceID} ]]
    then set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  ret=$(cf curl "/v2/service_instances/${_instanceID}" | jq ".entity.space_guid" "${JQOptions}")
  Result=$?
  echo "${ret}"
}

# Takes the GUID for a space and returns its name.
space_name_with_guid()
{
  local _spaceID="$1"
  if [[ -z ${_spaceID} ]]
    then set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  ret=$(cf curl "/v2/spaces/${_spaceID}" | jq ".entity.name" "${JQOptions}")
  Result=$?
  echo "${ret}"
}

# Takes a space guid and returns the GUID of the org which that space resides in.
org_guid_for_space()
{
  local _spaceID="$1"
  if [[ -z ${_spaceID} ]]
  then
    set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  ret=$(cf curl "/v2/spaces/${_spaceID}" | jq ".entity.organization_guid" "${JQOptions}")
  Result=$?
  echo "${ret}"
}

# Takes an organization's GUID and returns its name
org_name_with_guid()
{
  local _orgID="$1"
  if [[ -z ${_orgID} ]]
    then set -e; error_with "${FUNCNAME}:${LINENO}  No args given"
  fi
  ret=$(cf curl "/v2/organizations/${_orgID}" | jq ".entity.name" "${JQOptions}")
  Result=$?
  echo "${ret}"
}

error_with()
{
  echo -e "\033[31m$1\033[0m" >&2 
  exit 1
}

print_usage()
{
  echo -e "\
  \033[35musage:
      $0 <options> <instance_ids>
  options:
      -f <filename> | searches each newline separated GUID in the file given
                      after this argument
      -j            | gives the output in json format
      -M            | adds the -M tag to jq calls. Use with jq version >= 1.5\033[0m"
  exit 0
}

print_orphaned_instances()
{
  echo "The following instance IDs could be not be found:"
  for instance in "$@"
  do echo "${instance}"
  done
}

main()
{
  if [[ "$1" == "-h" || "$1" == "--help" ]]
    then print_usage
  fi
  local -a _orphanInstances
  local _instanceGUID _spaceGUID _spaceName _orgGUID _orgName
  local -a _inputs=()
  #These three variables are for tracking required column length for printf
  local _appLen="${#AppNameHeader}" _spaceLen="${#SpaceNameHeader}" _orgLen="${#OrgNameHeader}"
  local _getFilename=false
  for arg in $@
  do
    if [[ "${_getFilename}" == true ]]
    then
      local filename="${arg}"
      while read guid
        do _inputs+=("${guid}")
      done < "${filename}"
      _getFilename=false
    elif [[ "${arg}" == "-j" || "${arg}" == "--json" ]]
    then
      PrintJSON=true 
    elif [[ "${arg}" == "-f" || "${arg}" == "--file" ]]
    then 
      _getFilename=true
    elif [[ "${arg}" == "-M" || "${arg}" == "--no-color" ]]
    then
      JQOptions="-Mr"
    else
      _inputs+=("${arg}")
    fi
  done
  # Loop over each input instance_id, getting its information.
  for input in "${_inputs[@]}"
  do
    local _shouldContinue=false
    local -a _appGUIDs=()
    local -a _appNames=() 
    _instanceGUID="${input}"
    local _appGUIDsRaw=$(app_guids_bound_to "${_instanceGUID}")
    # Take the newline separated input and feed it into an array
    while read guid
    do
      _appGUIDs+=("${guid}")
    done <<<"${_appGUIDsRaw}"
    # If something went wrong... or there aren't any apps.
    if [[ (( $Result != 0 )) || (( ${#_appGUIDs[@]} == 0 )) ]]
    then
      _orphanInstances+=("${_instanceGUID}")
      continue
    fi
    for guid in "${_appGUIDs[@]}"
    do 
      if [[ "${guid}" == "" ]]
        then 
          _orphanInstances+=("${_instanceGUID}")
          _shouldContinue=true
          break
      fi

      local _thisAppName="$(app_name_with_guid ${guid})"
      if [[ $Result != 0 ]]
        then 
          _orphanInstances+=("${_instanceGUID}")
          _shouldContinue=true
          break
      fi
      _appNames+=("${_thisAppName}")
      if (( "${#_thisAppName}" > "${_appLen}" ))
        then _appLen="${#_thisAppName}"
      fi
    done
    if [[ "${_shouldContinue}" == true ]]
      then continue
    fi
    _spaceGUID=$(space_guid_for_service_instance "${_instanceGUID}")
    _spaceName=$(space_name_with_guid "${_spaceGUID}")
    if (( "${#_spaceName}" > "${_spaceLen}" ))
      then _spaceLen="${#_spaceName}"
    fi
    _orgGUID=$(org_guid_for_space "${_spaceGUID}")
    _orgName=$(org_name_with_guid "$_orgGUID")
    if (( "${#_orgName}" > "${_orgLen}" ))
      then _orgLen="${#_orgName}"
    fi
    local i=0
    for guid in "${_appGUIDs[@]}"
    do
      if [[ ${i} == 0 ]]
      then 
        InstanceGUIDs+=("${_instanceGUID}")
        OrgGUIDs+=("${_orgGUID}")
        OrgNames+=("${_orgName}")
        SpaceGUIDs+=("${_spaceGUID}")
        SpaceNames+=("${_spaceName}")
        AppGUIDs+=("${_appGUIDs[0]}")
        AppNames+=("${_appNames[0]}")
        NumInstancesFound=$(( NumInstancesFound + 1 ))
      else
        Rows+=("^ ^ ^ ^ ^ ${_appGUIDs[${i}]} ${_appNames[${i}]}")
        InstanceGUIDs+=("^")
        OrgGUIDs+=("^")
        OrgNames+=("^")
        SpaceGUIDs+=("^")
        SpaceNames+=("^")
        AppGUIDs+=(${_appGUIDs[${i}]})
        AppNames+=(${_appNames[${i}]})
      fi
      i=$((i+1))
    done
  done

  # Printing time.
  if [[ "${PrintJSON}" == true ]]
  then
    # Format as JSON
    printf "{ \"total_found\": %d, \"total_not_found\": %d, \"found\": [" "${NumInstancesFound}" "${#_orphanInstances[@]}"
    local _separator=""
    local _numApps=0
    i=0
    for row in "${InstanceGUIDs[@]}"
    do
      # If this is a new instance id...
      if [[ "${row[${i}]}" != "^" ]]
      then
        printf "%s { \"instance_id\": \"%s\", \"org_id\": \"%s\", \"org_name\": \"%s\", \"space_id\": \"%s\", \"space_name\": \"%s\", \"apps\": [ { \"id\": \"%s\", \"name\": \"%s\" }" \
          "${_separator}" "${InstanceGUIDs[${i}]}" "${OrgGUIDs[${i}]}" "${OrgNames[${i}]}" "${SpaceGUIDs[${i}]}" "${SpaceNames[${i}]}" "${AppGUIDs[${i}]}" "${AppNames[${i}]}"
        _numApps=1
      else
        # Otherwise, just add it to the app list.
        printf ", { \"id\": \"%s\", \"name\": \"%s\" }" "${AppGUIDs[${i}]}" "${AppNames[${i}]}"
        _numApps=$(( _numApps + 1 ))
      fi
      _separator="], \"total_apps\": ${_numApps}}, "
      i=$((i+1))
    done
    if (( "${#InstanceGUIDs[@]}" > 0 ))
    then printf "], \"total_apps\":${_numApps}}"
    fi
    printf "], \"not_found\": ["
    _separator=""
    for inst in "${_orphanInstances[@]}"
    do
      printf "%s \"%s\"" "${_separator}" "${inst}"
      _separator=","
    done
    printf "] }" 
  else
    #TABLE FORMAT
    # What did we find?
    formatString="%36s | %36s | %${_orgLen}s | %36s | %${_spaceLen}s | %36s | %${_appLen}s\n"
    printf "${formatString}" \
      "${InstanceGUIDHeader}" "${OrgGUIDHeader}" "${OrgNameHeader}" \
      "${SpaceGUIDHeader}" "${SpaceNameHeader}" "${AppGUIDHeader}" "${AppNameHeader}"
    i=0
    for row in "${InstanceGUIDs[@]}"
    do
      printf "${formatString}" "${InstanceGUIDs[${i}]}" "${OrgGUIDs[${i}]}" "${OrgNames[${i}]}" "${SpaceGUIDs[${i}]}" "${SpaceNames[${i}]}" "${AppGUIDs[${i}]}" "${AppNames[${i}]}" 
      i=$((i+1)) 
    done 
    # What couldn't we find?
    if (( "${#_orphanInstances}" > 0 ))
      then 
        echo
        print_orphaned_instances "${_orphanInstances[@]}"
    fi
  fi
}

main $@

